### ISSUE TITLE
undefined is not an object RCTWebViewBridgeManager.NavigationType

### ISSUE THREAD

**Issue by bec-smith** [Partido-Asia/react-native-drawpad#1]
Any idea on how to fix this? Here is the error screen and the code:

![img_0943](https://user-images.githubusercontent.com/24505969/33048098-0f15845a-ce0e-11e7-91e3-dc601778ce47.PNG)

<img width="509" alt="screen shot 2017-11-20 at 4 16 05 pm" src="https://user-images.githubusercontent.com/24505969/33048127-29533470-ce0e-11e7-8c70-3534ea42035a.png">

**Comment by Partido-Asia** [comment]
Hi we just update the package, would you try again?

**Comment by dannyyaou** [comment]
I am gonna close the issue due to the fact that we just update the module
If anyone comes to any issue, please let us know
